# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 531, 391))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 181, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cmbbx1 = QtWidgets.QComboBox(self.groupBox)
        self.cmbbx1.setGeometry(QtCore.QRect(20, 60, 151, 22))
        self.cmbbx1.setObjectName("cmbbx1")
        self.Btn1 = QtWidgets.QPushButton(self.groupBox)
        self.Btn1.setGeometry(QtCore.QRect(180, 60, 31, 23))
        self.Btn1.setObjectName("Btn1")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 201, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Lbl1 = QtWidgets.QLabel(self.groupBox)
        self.Lbl1.setGeometry(QtCore.QRect(20, 130, 47, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Lbl1.setFont(font)
        self.Lbl1.setObjectName("Lbl1")
        self.Btn2 = QtWidgets.QPushButton(self.groupBox)
        self.Btn2.setGeometry(QtCore.QRect(10, 290, 75, 23))
        self.Btn2.setObjectName("Btn2")
        self.Btn3 = QtWidgets.QPushButton(self.groupBox)
        self.Btn3.setGeometry(QtCore.QRect(130, 290, 75, 23))
        self.Btn3.setObjectName("Btn3")
        self.Btn4 = QtWidgets.QPushButton(self.groupBox)
        self.Btn4.setGeometry(QtCore.QRect(260, 290, 75, 23))
        self.Btn4.setObjectName("Btn4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Módulo ráster"))
        self.groupBox.setTitle(_translate("MainWindow", "Datos de entrada"))
        self.label.setText(_translate("MainWindow", "Selecciona el archivo"))
        self.Btn1.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Sistema de referencia geoespacial"))
        self.Lbl1.setText(_translate("MainWindow", "SCRG"))
        self.Btn2.setText(_translate("MainWindow", "Ayuda"))
        self.Btn3.setText(_translate("MainWindow", "Ejecutar"))
        self.Btn4.setText(_translate("MainWindow", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
